export enum NotificationType {
  PROPOSAL_RECEIVED    = "PROPOSAL_RECEIVED",
  PROPOSAL_ACCEPTED    = "PROPOSAL_ACCEPTED",
  PROPOSAL_REJECTED    = "PROPOSAL_REJECTED",
  NEW_MESSAGE          = "NEW_MESSAGE",
  PAYMENT_RECEIVED     = "PAYMENT_RECEIVED",
  PROPERTY_APPROVED    = "PROPERTY_APPROVED",
  PROPERTY_REJECTED    = "PROPERTY_REJECTED",
  SHOWING_SCHEDULED    = "SHOWING_SCHEDULED",
  INSPECTION_SCHEDULED = "INSPECTION_SCHEDULED",
}
